Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
StringLiterals:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
